import type { ProviderPreset } from '../../types'

export const providerPresets: ProviderPreset[] = [
  {
    id: 'anthropic-official',
    label: 'Claude 官方',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://platform.claude.com/',
    docsUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
    description: '官方 Claude 接口，兼容性最好，适合先验证应用主链路。',
    defaultBaseUrl: 'https://api.anthropic.com',
    recommendedModels: ['claude-sonnet-4-20250514', 'claude-opus-4-20250514'],
    readiness: 'ready',
    includeAnthropicVersionHeader: true,
  },
  {
    id: 'aliyun-bailian',
    label: '阿里云百炼',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://bailian.console.aliyun.com/cn-beijing/?tab=coding-plan#/efm/index',
    docsUrl: 'https://help.aliyun.com/zh/model-studio/coding-plan-faq',
    description: '阿里云百炼 Coding Plan 的 Anthropic 兼容入口。',
    defaultBaseUrl: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
    recommendedModels: ['qwen3-max', 'qwen-plus-latest', 'glm-5', 'kimi-k2.5'],
    readiness: 'ready',
    includeAnthropicVersionHeader: false,
  },
  {
    id: 'tencent-coding-plan',
    label: '腾讯云',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://cloud.tencent.com/act/pro/codingplan',
    docsUrl: 'https://cloud.tencent.com/document/product/1772/128951',
    description: '腾讯云 Coding Plan 的 Anthropic 兼容接口。',
    defaultBaseUrl: 'https://api.lkeap.cloud.tencent.com/plan/anthropic',
    recommendedModels: ['glm-5', 'deepseek-v3.1', 'hunyuan-t1'],
    readiness: 'ready',
    includeAnthropicVersionHeader: false,
  },
  {
    id: 'baidu-qianfan',
    label: '百度千帆',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://cloud.baidu.com/product/codingplan.html',
    docsUrl: 'https://cloud.baidu.com/doc/qianfan/s/imlg0beiu',
    description: '百度千帆提供 Anthropic 兼容 URL Path，可接 Claude Code 生态。',
    defaultBaseUrl: 'https://qianfan.baidubce.com/anthropic/coding',
    recommendedModels: ['qianfan-code-latest', 'kimi-k2.5', 'glm-5'],
    readiness: 'ready',
    includeAnthropicVersionHeader: false,
  },
  {
    id: 'volcengine-coding-plan',
    label: '火山引擎',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://www.volcengine.com/activity/codingplan',
    docsUrl: 'https://www.volcengine.com/docs/82379/1928262',
    description: '火山引擎 Coding Plan 已公开 Anthropic 兼容地址。',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/coding',
    recommendedModels: ['doubao-seed-code', 'doubao-seed-2.0-pro', 'MiniMax-M2.5'],
    readiness: 'ready',
    includeAnthropicVersionHeader: false,
  },
  {
    id: 'minimax-coding-plan',
    label: 'MiniMax',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://platform.minimaxi.com/subscribe/coding-plan',
    docsUrl: 'https://platform.minimaxi.com/docs/guides/text-ai-coding-tools',
    description: 'MiniMax 官方文档已给出 Anthropic-compatible base URL。',
    defaultBaseUrl: 'https://api.minimaxi.com/anthropic',
    recommendedModels: ['MiniMax-M2.5', 'MiniMax-M2.5-highspeed'],
    readiness: 'ready',
    includeAnthropicVersionHeader: false,
  },
  {
    id: 'zai-glm-coding',
    label: '智谱 GLM',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://open.bigmodel.cn/glm-coding',
    docsUrl: 'https://open.bigmodel.cn/dev/api',
    description: '智谱以 Z.AI 文档提供 Claude Code / Anthropic 兼容接入说明。',
    defaultBaseUrl: 'https://api.z.ai/api/anthropic',
    recommendedModels: ['glm-5', 'glm-4.7', 'glm-4.5-air'],
    readiness: 'ready',
    includeAnthropicVersionHeader: false,
  },
  {
    id: 'kimi-code',
    label: 'Kimi Code',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://www.kimi.com/code',
    docsUrl: 'https://platform.kimi.com/docs/guide/agent-support',
    description: 'Kimi 官方文档提供 Anthropic 请求地址与模型示例。',
    defaultBaseUrl: 'https://api.moonshot.cn/anthropic',
    recommendedModels: ['kimi-k2.5', 'kimi-k2-thinking'],
    readiness: 'ready',
    includeAnthropicVersionHeader: false,
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://platform.deepseek.com/',
    docsUrl: 'https://api-docs.deepseek.com/zh-cn/guides/anthropic_api',
    description: 'DeepSeek 官方提供 Anthropic-compatible 接口，可直接按兼容方式接入。',
    defaultBaseUrl: 'https://api.deepseek.com/anthropic',
    recommendedModels: ['deepseek-chat', 'deepseek-reasoner'],
    readiness: 'ready',
    includeAnthropicVersionHeader: false,
  },
  {
    id: 'custom',
    label: '自定义',
    protocol: 'anthropic-compatible',
    officialUrl: 'https://docs.anthropic.com/en/api/messages',
    description: '给没有内置预设或需要代理网关的接口手动填值。',
    recommendedModels: [],
    readiness: 'manual',
    includeAnthropicVersionHeader: false,
  },
]

export function getPresetById(presetId: string | null) {
  if (!presetId) {
    return null
  }

  return providerPresets.find((preset) => preset.id === presetId) ?? null
}
